global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "trading_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Backend API metrics
  - job_name: 'trading-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend metrics (if implemented)
  - job_name: 'trading-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL/TimescaleDB metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # WebSocket metrics
  - job_name: 'websocket'
    static_configs:
      - targets: ['websocket:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Price poller metrics
  - job_name: 'price-poller'
    static_configs:
      - targets: ['price-poller:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
